### ISSUE TITLE
调用sdk的获取账号权限方法返回结果与实际不符

### ISSUE THREAD

**Issue by zhangzp0127** [CAICT-DEV/BIF-Core-SDK#2]
版本：release/1.0.1
调试工具：IntelliJ IDEA 2022.1.3 (Ultimate Edition)
操作步骤：断点调试获取账号权限。
BIFAccountPrivResponse response = sdk.getBIFAccountService().getAccountPriv(request);
进入getAccountPriv方法
<img width="498" alt="微信截图_20230319095546" src="https://user-images.githubusercontent.com/20589704/226149817-0ea29acf-46cd-4edc-ab21-bd0f0b87f8d9.png">
上图中resultInfo结果中type为1，继续断点下一步，可以看到type变为了0
<img width="389" alt="微信截图_20230319095652" src="https://user-images.githubusercontent.com/20589704/226149863-4a921898-7c94-411f-b80c-c7c2ce970b05.png">
通过查看cn.bif.model.response.result.data.BIFTypeThreshold类发现存在两个setType方法
<img width="702" alt="微信截图_20230319095807" src="https://user-images.githubusercontent.com/20589704/226149964-7efc6772-8e49-4074-aa56-dcd788483bca.png">
不清楚是bug还是正常逻辑。

**Comment by Caict-GuoShiJie** [comment]
您好，经排查是bug，我们尽快修复，感谢支持，您可以加入我们技术交流群进行问题咨询，感谢
![技术交流群](https://user-images.githubusercontent.com/90613859/226283039-7156acc0-5cc0-4c18-ad30-b0b0222aa466.jpg)

**Comment by Caict-GuoShiJie** [comment]
@zhangzp0127  请关注，感谢
