### ISSUE TITLE
使用 solidity 的方式调用 bifContractInvoke ，input中的 string 中的中文无法正常存储

### ISSUE THREAD

**Issue by zealot0307** [CAICT-DEV/BIF-Core-SDK#3]
调用查询方法返回结果为乱码
![image](https://user-images.githubusercontent.com/16589219/234163879-4fea7b8c-8499-4f30-9bc7-375d7865bd65.png)

**Comment by Caict-GuoShiJie** [comment]
solidity合约目前不支持存储中文，您可加入我们技术交流群，感谢支持
![8138a158c080cc4bc6d0df90f83b4ff](https://user-images.githubusercontent.com/90613859/234192679-ff57be32-57d1-4909-b06a-6b4e6aff6567.jpg)

**Comment by CAICT-DEV** [comment]
> 调用查询方法返回结果为乱码 ![image](https://user-images.githubusercontent.com/16589219/234163879-4fea7b8c-8499-4f30-9bc7-375d7865bd65.png)

当前版本已经解决。
